<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="ProjektDemo.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.clients" Member="clients">
    <Type Name="clients">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="data_add" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_edit" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="clients_rental" Member="rental" ThisKey="id" OtherKey="clients_id" Type="rental" />
    </Type>
  </Table>
  <Table Name="dbo.rental" Member="rental">
    <Type Name="rental">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clients_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="video_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_add" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_edit" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="clients_rental" Member="clients" ThisKey="clients_id" OtherKey="id" Type="clients" IsForeignKey="true" />
      <Association Name="video_rental" Member="video" ThisKey="video_id" OtherKey="id" Type="video" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.status" Member="status">
    <Type Name="status">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="status_video" Member="video" ThisKey="id" OtherKey="status_id" Type="video" />
    </Type>
  </Table>
  <Table Name="dbo.type" Member="type">
    <Type Name="type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="type_video" Member="video" ThisKey="id" OtherKey="type_id" Type="video" />
    </Type>
  </Table>
  <Table Name="dbo.video" Member="video">
    <Type Name="video">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="new" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_add" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_edit" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="video_rental" Member="rental" ThisKey="id" OtherKey="video_id" Type="rental" />
      <Association Name="type_video" Member="type" ThisKey="type_id" OtherKey="id" Type="type" IsForeignKey="true" />
      <Association Name="status_video" Member="status" ThisKey="status_id" OtherKey="id" Type="status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_video" Member="v_video">
    <Type Name="v_video">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="new" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_add" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_edit" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>